FROM openjdk:8-nanoserver
MAINTAINER bradfordbarnhill@gmail.com
WORKDIR /app

ADD build/libs/barcode-api.jar .

VOLUME c:/tmp

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "barcode-api.jar"]