server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
  servlet:
    session:
      timeout: 10s
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/pnuema.p12
    key-store-password: ${BARCODE_SSL_PASSWORD}
    key-alias: 1

