server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
  servlet:
    session:
      timeout: 10s
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG